currentQers = [
  { name: "Arian van Gend", handle:"arian" },
  { name: "Arjen van der Ende", handle: "arjen" },
  { name: "Bart Kiers", handle: "bart" },
  { name: "Bas Warmerdam", handle:"bas" },
  { name: "Benjamin de Jager", handle:"benjamin" },
  { name: "Bob van Oorschot", handle:"bob", phone: "070-4452352" },
  { name: "Bram Lohman", handle:"braml", imageStatic: "anonymous.jpg", imageAnimated: "anonymous.jpg" },
  { name: "Bram Stege", handle:"bram", imageStatic: "anonymous.jpg", imageAnimated: "anonymous.jpg" },
  { name: "Chris Waalberg", handle:"chris" , phone: "06-16170184" },
  { name: "Christiaan Hees", handle:"christiaan", tumblr: "www-chees-info" },
  { name: "Corina Maduro", handle:"corina" },
  { name: "Cynthia Wijntje", handle:"cynthia" },
  { name: "Frank Raterink", handle:"frank", web: "http://www.franklabs.nl" },
  { name: "Gerard Dorst", handle:"gerard" },
  { name: "Guido Bouman", handle:"guido" },
  { name: "Guus Goossens", handle:"guus" },
  { name: "Herman Banken", handle:"herman", web: "http://hermanbanken.nl/" },
  { name: "Ineke Scheffers", handle:"ineke", tumblr: "fyineke" },
  { name: "Jaap Taal", handle:"jaap" },
  { name: "Jaap Mengers", handle: "jaapm" },
  { name: "Jasper Haggenburg", handle:"jasperh", web: "http://jpunt.nl" },
  { name: "Jasper Kaizer", handle:"jasper" },
  { name: "Jeroen Gijsman", handle:"jeroen" },
  { name: "Jimmy Aupperlee", handle:"jimmy" },
  { name: "Joel de Nes", handle:"joel", imageStatic: "anonymous.jpg", imageAnimated: "anonymous.jpg" },
  { name: "Johan Huijkman", handle:"johan", tumblr: "huijkman" },
  { name: "Kamil Afsar", handle:"kamil" },
  { name: "Kars Veling", handle:"kars" },
  { name: "Katja Hollaar", handle:"katja" },
  { name: "Korjan van Wieringen", handle:"korjan" },
  { name: "Kristin Rieping", handle:"kristin" },
  { name: "Laurens van den Oever", handle:"laurens" },
  { name: "Leonard Punt", handle:"leonard" },
  { name: "Lukas van Driel", handle:"lukas", phone: "06-14141544", web: "http://developer.3l.nl/", tumblr: "lukasvan3l" },
  { name: "Marcel Duin", handle:"marcel", web: "http://webglmarcel.q42.net/" },
  { name: "Mark van Straten", handle:"mark", phone: "070-4452347" },
  { name: "Martin Kool", handle:"martin", web: "http://martinkool.com/" },
  { name: "Mathijs Bernson", handle: "mathijsb", imageStatic: "anonymous.jpg", imageAnimated: "anonymous.jpg" },
  { name: "Mathijs Kadijk", handle: "mathijs", web: "http://mathijskadijk.nl/", tumblr: "mathijskadijk" },
  { name: "Michiel Post", handle:"michiel", web: "http://michielpost.nl/", tumblr: "michielpostnl" },
  { name: "Rahul Choudhury", handle:"rahul", tumblr: "primigenus" },
  { name: "Remco Veldkamp", handle:"remco", web: "http://realstuffforabstractpeople.com/" },
  { name: "Richard Lems", handle:"richard" },
  { name: "Rik Nijessen", handle:"rikn", imageStatic: "anonymous.jpg", imageAnimated: "anonymous.jpg" },
  { name: "Rob Lokhorst", handle:"rob" },
  { name: "Roelf-Jan de Vries", handle:"roelfjan", web: "http://www.roelf-jandevries.nl", tumblr: "roelfjandevries" },
  { name: "Sander de Vos", handle:"sander" },
  { name: "Sander Ploegsma", handle:"sanderp", web:"https://sanderp.nl" },
  { name: "Silvy van Houdt", handle:"silvy" },
  { name: "Sjoerd Visscher", handle:"sjoerd", web: "http://w3future.com/" },
  { name: "Stef Brooijmans", handle:"stef", phone: "070-4452351" },
  { name: "Suzanne Waalberg", handle:"suzanne" },
  { name: "Taco Ekkel", handle: "taco" },
  { name: "Ted de Koning", handle:"ted" },
  { name: "Thijs Suijten", handle:"thijs", tumblr: "tsuijten" },
  { name: "Tim Logtenberg", handle:"timl", phone: "070-4452360", email: "tim" },
  { name: "Tim van Deursen", handle:"timd", phone: "070-4452361" },
  { name: "Tim van Steenis", handle:"tims", web:"http://www.vansteenis-photography.nl/", tumblr: "timvansteenis" },
  { name: "Tobias Stikvoort", handle:"tobias", imageStatic: "anonymous.jpg", imageAnimated: "anonymous.jpg" },
  { name: "Tom Lokhorst", handle:"tom", web: "http://tom.lokhorst.eu/", tumblr: "tomlokhorst" },
  { name: "Tomas Harkema", handle:"tomas" },
  { name: "Wouter Horsman", handle:"wouterh", imageStatic: "anonymous.jpg", imageAnimated: "anonymous.jpg" },
  { name: "Wouter van Drunen", handle: "wouter" }
];

export { currentQers }
